### ISSUE TITLE
Unable to run (java.lang.ExceptionInInitializerError)

### ISSUE THREAD

**Issue by benhid** [bio-ontology-research-group/el-embeddings#14]
Hello,

I am having trouble following the _How to run_ section to set up the environment.

When running `Normalizer.groovy` (first step) I got the following exception:

```sh
> groovy -cp jar/*.jar Normalizer.groovy -I ontology.owl -o normalized_axioms
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/el-embeddings/Normalizer.groovy: 37: unable to resolve class CliBuilder
 @ line 37, column 11.
   def cli = new CliBuilder()
             ^

1 error
```

Solved by importing `CliBuilder` as follows:

```groovy
import groovy.cli.commons.CliBuilder
```

But then, the following exception occurs:

```sh
> groovy -cp jar/*.jar Normalizer.groovy -i ontology.owl -o normalized_axioms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:91)
        at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:103)
        at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
        at Normalizer.run(Normalizer.groovy:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5b218417
        at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
        ... 26 more
```

`Normalizer.groovy` line 62: 
```groovy
OWLOntologyManager manager = OWLManager.createOWLOntologyManager()
```

I am using Groovy 4.0.1 installed from [brew](https://formulae.brew.sh/formula/groovy) and openjdk-12.0.1. Any ideas?

Thanks.

**Comment by WangYao-GoGoGo** [comment]
@benhid  hi, Did you solve this problem? Could you share your method with me?
